* fejl [2022-11-02 on.]

  - bør en kunne → bør man kunne
  - (som) er festet → (som) sitter fast LSX
  - er på plass → sidder riktigt??? for spesifikt
  - -itt → -itis eller enkel t -it, hydroksylapatit
  - brukes til å bite av og tygge mat → brukes til å bide over??
  - de vil etterhvert bli «spist[e] opp» – ikkje adj.pp her! DIS
  - bamblesyke→bornholmsk syge
  - slå seg til i → angribe
  - Barnet tager efter → Barnet rækker ud efter

* kommafejl [2022-11-02 on.]--[2022-11-03 to.]

  - skole og andre voksne[,] som barn har nærkontakt med
  - Toksoplasmose er en protozosykdom[,] som blant annet kan ramme gravide kvinner[,] uten at disse selv blir syke, men barnet kan bli født med en meget alvorlig encefalitt.
  - Det er meget[,] som→der tyder på
  - Det har lenge vært kjent[,] at barnets psykiske u…
  - Det→Der er mange[,] som har sykdommen i lett grad
  - indreb i munden[,] og kæbe- ansigtsskelettet.
    (ikkje komma ved det innskotet på slutten av setninga – kan me laga reglar for det?)
  - Cøliaki er en tynntarmsykdom[,] som skyldes[,] at den[,] som har sykdommen[,] ikke tåler kornproteinet gluten.
  - Vi skiller mellom skulderleddet (humeri)[,] som er forbindelsen mellom A og B.
  - Formen på leddhodet tilsier[,] at overarmsbeinet kan beveges i alle retninger.
  - Leddet har en kort hals (collum humeri), hvor vi finner to beinknuter (tuberculum majus & minus)[,] som er feste for noen av skuldermusklene (rotatormansjetten).
  - På hver side av leddflaten finner vi den indre og ytre albueknoken (epicondylus medialis & lateralis)[,] som kan kjennes under huden.
  - arteria ulnaris[,] som følger albuebeinet, og arteria radialis[,] som følger spolebeinet.


* fejl [2022-11-03 to.]
  - De→Dem med helsefaglig bakgrunn
  - lem → legemsdel
  - bli frigjort fra arbeidet med → slet ikke lenger bruges til
  - gange på bakken → gang på jorden (ikkje «bagen»)
  - Bevegelser i skulderleddet gjør det mulig[ikkje komma!] å føre armen ut fra kroppen
  - å feste→fæstne overarmen til skulderbladet
  - Vi skiller→skelner mellom to uttrykk
  - Vi skiller fra → adskille
  - Det nedre (*distale) ledhodet→ledhoved (RTX-regel for parentes!)
  - Den fortsetter gjennom armhulen (axilla)[ikkje komma!] som arteria axillaris og ned langs overarmens innside som arteria brachialis.
  - ulna<n>, select tidleg i DIS
  - Man kan kjenne→mærke kanten av albuebeinet
    - kjenne→kende igjen
    - kjenne→kende en venn
    - kjenne→føle seg
  - angive ET sted (når man skal angi sted)
  - skrueledd → drejeled
  - valseformet → cylinderformet
  - en mængde → en lang række
  - utvidet kunnskaben → udvidet vores viden
    denne kunnskapen → den viden
  - vevenes bygning → vævenes opbygning
  - I håndflaten har de to arteriene bueformede forbindelser (anastomoser),[fjern komma!] med blodkar ut til fingrene.


