* fejl [2022-11-02 on.]

  - bør en kunne → bør man kunne
  - er på plass → sidder riktigt??? for spesifikt
  - -itt → -itis eller enkel t -it, hydroksylapatit
  - brukes til å bite av og tygge mat → brukes til å bide over??
  - de vil etterhvert bli «spist[e] opp» – ikkje adj.pp her! DIS
  - slå seg til i → angribe
  - Barnet tager efter → Barnet rækker ud efter

* kommafejl [2022-11-02 on.]--[2022-11-03 to.]

  legg til komma:
  - skole og andre voksne[,] som barn har nærkontakt med
  - Vi skiller mellom skulderleddet (humeri)[,] som er forbindelsen mellom A og B.
  - Leddet har en kort hals (collum humeri), hvor vi finner to beinknuter (tuberculum majus & minus)[,] som er feste for noen av skuldermusklene (rotatormansjetten).
  - På hver side av leddflaten finner vi den indre og ytre albueknoken (epicondylus medialis & lateralis)[,] som kan kjennes under huden.
  - arteria ulnaris[,] som følger albuebeinet, og arteria radialis[,] som følger spolebeinet.

  fjern komma:
  - Bevegelser i skulderleddet gjør det mulig[ikkje komma!] å føre armen ut fra kroppen
  - Den fortsetter gjennom armhulen (axilla)[ikkje komma!] som arteria axillaris og ned langs overarmens innside som arteria brachialis.
  - I håndflaten har de to arteriene bueformede forbindelser (anastomoser)[fjern komma!] med blodkar ut til fingrene.
  - indgreb i munden[ikkje komma!] og kæbe- ansigtsskelettet.

* fejl [2022-11-03 to.]
  - De→Dem med helsefaglig bakgrunn
  - bli frigjort fra arbeidet med → slet ikke lenger bruges til
  - Det nedre (*distale) ledhodet→ledhoved (RTX-regel for parentes!)
  - angive ET sted (når man skal angi sted)
  - vevenes bygning → vævenes opbygning


