#!/bin/bash

# Accepts one pair per line, separated by :, dan first, e.g.
# vej:vei

# Run with first argument "inflected" to also accept input with
# inflected forms (not just lemmas), at the cost of more false
# positives to check, e.g.
#
# $ echo 'vejene:veiene' | dev/add-words inflected > new-words.dix

if [[ $1 = inflected ]]; then
    script=add-words-inflected.awk
else
    script=add-words.awk
fi

make -q langs
if [[ $? = 1 ]]; then
    echo "make -j langs # do this first" 1>&2
fi


tmpd=$(mktemp -dt apertium-add-words.XXXXXXXXXX)
echo "${tmpd}" >&2

cat >"${tmpd}/bi"

echo "${tmpd}/dan" >&2
cut -f1 -d: "${tmpd}"/bi |apertium-destxt -n |apertium -f none  -d ../apertium-dan dan-morph|apertium-retxt >"${tmpd}"/dan

echo "${tmpd}/nob" >&2
cut -f2 -d: "${tmpd}"/bi |apertium-destxt -n |apertium -f none  -d ../apertium-nob nob-morph|apertium-retxt >"${tmpd}"/nob

echo "${tmpd}/dan-known" >&2
cut -f1 -d: "${tmpd}"/bi|apertium-destxt -n |apertium -f none -d . dan-nob-morph  |apertium-retxt |grep '^\^[^*+]*\$$'|sed 's,/.*,,'|tr -d ^ >"${tmpd}"/dan-known
echo "${tmpd}/nob-known" >&2
cut -f2 -d: "${tmpd}"/bi|apertium-destxt -n |apertium -f none -d . nob-dan-morph|apertium-retxt |grep '^\^[^*+]*\$$'|sed 's,/.*,,'|tr -d ^ >"${tmpd}"/nob-known

awk -v tmpd="${tmpd}" -f "$(dirname "$0")"/"${script}" /dev/null
