#!/bin/bash

parsuf="__adj"

for mono in dan nno nob; do
    grep -ho "lm=\".*${parsuf}" ../apertium-${mono}/*dix | sed 's/lm="//;s/".*/./' >/tmp/"${parsuf}".${mono}
done

echo 'agt:agd$
dst:sst$
st:sst$
gget:gd$
ild:ill$
kær:kjær$
lad:lat$
ldt:lt$
yg:ygg$
ør:ørr$
und:unn$
vag:vak$
givet:gitt$
at:att$
et:ett$
kold:kald$
ut:utt$
set:sete$
is:iss$
stærk:sterk$
ædt:edd$
ård:ard$
agne:anje$
eret:ert$
el:ell$
uld:ull$
tørre:tørke$
æle:ele$
øbe:øpe$
ide:ite$
yge:yke$
drage:dra$
abe:ape$
ige:ike$
jse:ise$
uge:uke$
æve:eve$
øde:øte$
ege:eike$
gne:kne$
ejle:eile$
oge:oke$
ejde:eide$
ade:ate$
eje:eie$
øje:øye$
yde:yte$
age:ake$
dse:sse$
æse:ese$
øge:øke$
ibe:ipe$
ege:eke$
øbe:øpe$
lde:lle$
ælde:elle$
nde:nne$
gte:kte$
ind:inn
høj:høy
bag:bak
mod:mot
præ:pre
eft:ett
gen:gjen
cen:sen
børn:barn
olie:olje
mad:mat
fod:fot
bog:bok
græ:gre
bræ:bre
skæ:skjæ
rig:rik
kød:kjøtt
vær:ver
mag:mak
træ:tre
nati:nasj
lig:lik
kartoffel:potet
fælles:felles
læse:lese
afg:avg
uds:uts
ops:opps
mælk:melk
ken:kjen
have:hage
amt:fylke
landsby:bygde
jagt:jakt
fæng:feng
bjer:ber
syg:syk
soc:sos
slæ:sle
sag:sak
opv:oppv
opl:oppl
læg:leg
ker:kjer
afs:avs
udv:utv
rej:rei
opt:oppt
kør:kjør
vej:vei' >/tmp/dan2nob

dan2nob () {
    awk -F: 'BEGIN{ while(getline<"/tmp/dan2nob")dan2nob[$2][$1]++ }
{
    b=$0
    for(d in ds) delete ds[d]
    ds[$0]++
    for(pat in dan2nob) for(rep in dan2nob[pat]) for(d in ds) {
        gsub(pat, rep, d)
        ds[d]++
    }
    for(d in ds) print d":"b
}
'
}

join -j1 -t: \
     <(tr -d '*.' < /tmp/"${parsuf}".dan | sort -k1b,1 -t: ) \
     <(tr -d '*.' < /tmp/"${parsuf}".nob | dan2nob | sort -k1b,1 -t: ) \
    | grep -v '0-9' \
    | dev/add-words
